# This file was generated by GoReleaser. DO NOT EDIT.
cask "d8s" do
  version "1.1.1"

  on_macos do
    on_arm do
      sha256 "fa58b90e19bf10097289ca4546c02c87dab041514f0f269aa108de5497def246"
      url "https://github.com/ekosup/d8s/releases/download/v#{version}/d8s_#{version}_darwin_arm64.tar.gz"
    end
    on_intel do
      sha256 "2102a9f0cc8acdc06cd7575c73023b033d7a2a49beb5da85462ee2c7501f6b9c"
      url "https://github.com/ekosup/d8s/releases/download/v#{version}/d8s_#{version}_darwin_amd64.tar.gz"
    end
  end
  on_linux do
    on_arm do
      sha256 "250e1d15a8547a9ba5bda18575b42dea9f1b3d6611a15da3d1962214875c0600"
      url "https://github.com/ekosup/d8s/releases/download/v#{version}/d8s_#{version}_linux_arm64.tar.gz"
    end
    on_intel do
      sha256 "dbb34e17531f2dcab1dcec5d39cf8e282726607fdcc87a7f0318010ef6d50c23"
      url "https://github.com/ekosup/d8s/releases/download/v#{version}/d8s_#{version}_linux_amd64.tar.gz"
    end
  end

  name "d8s"
  desc "Terminal UI for Docker Engine and Docker Swarm"
  homepage "https://github.com/ekosup/d8s"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "d8s"

  # No zap stanza required
end
